/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package eulerproject.Problems;

/**
 *
 * @author Charlie
 */
public class Problem_2 {
    /**
     * Problem 2 ---
     * Each new term in the Fibonacci sequence is generated by adding the 
     * previous two terms. By starting with 1 and 2, 
     * the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
     * By considering the terms in the Fibonacci sequence whose 
     * values do not exceed four million, 
     * find the sum of the even-valued terms.
     *  
     */
    public String Solve() {
        int sum = 0;
        int million = (int) Math.pow(10, 6);
        int value1 = 1;
        int value2 = 1;
        while (value2 < (4 * million)) {
            int nextNum = value1 + value2;
            if (nextNum % 2 == 0) 
                sum += nextNum;
            value1 = value2;
            value2 = nextNum;
        }
        return "The solution is: " + sum;
    }
}
